// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MetricStorer is an autogenerated mock type for the MetricStorer type
type MetricStorer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MetricStorer) Close() {
	_m.Called()
}

// Ping provides a mock function with given fields: ctx
func (_m *MetricStorer) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreDBValue provides a mock function with given fields: ctx
func (_m *MetricStorer) RestoreDBValue(ctx context.Context) {
	_m.Called(ctx)
}

// SaveDBValue provides a mock function with given fields: ctx
func (_m *MetricStorer) SaveDBValue(ctx context.Context) {
	_m.Called(ctx)
}
