// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// MetricStore is an autogenerated mock type for the MetricStore type
type MetricStore struct {
	mock.Mock
}

// Configure provides a mock function with given fields: ctx, wg
func (_m *MetricStore) Configure(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

// NotifyUpdateDBValue provides a mock function with given fields: ctx
func (_m *MetricStore) NotifyUpdateDBValue(ctx context.Context) {
	_m.Called(ctx)
}
