// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	metric "github.com/djokcik/praktikum-go-devops/internal/metric"
	mock "github.com/stretchr/testify/mock"
)

// CounterService is an autogenerated mock type for the CounterService type
type CounterService struct {
	mock.Mock
}

// GetOne provides a mock function with given fields: ctx, name
func (_m *CounterService) GetOne(ctx context.Context, name string) (metric.Counter, error) {
	ret := _m.Called(ctx, name)

	var r0 metric.Counter
	if rf, ok := ret.Get(0).(func(context.Context, string) metric.Counter); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(metric.Counter)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Increase provides a mock function with given fields: ctx, name, value
func (_m *CounterService) Increase(ctx context.Context, name string, value metric.Counter) error {
	ret := _m.Called(ctx, name, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metric.Counter) error); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx
func (_m *CounterService) List(ctx context.Context) ([]metric.Metric, error) {
	ret := _m.Called(ctx)

	var r0 []metric.Metric
	if rf, ok := ret.Get(0).(func(context.Context) []metric.Metric); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric.Metric)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, name, value
func (_m *CounterService) Update(ctx context.Context, name string, value metric.Counter) (bool, error) {
	ret := _m.Called(ctx, name, value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, metric.Counter) bool); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, metric.Counter) error); ok {
		r1 = rf(ctx, name, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: ctx, name, value, hash
func (_m *CounterService) Verify(ctx context.Context, name string, value metric.Counter, hash string) bool {
	ret := _m.Called(ctx, name, value, hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, metric.Counter, string) bool); ok {
		r0 = rf(ctx, name, value, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
