// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	sync "sync"
)

// DatabaseService is an autogenerated mock type for the DatabaseService type
type DatabaseService struct {
	mock.Mock
}

// Open provides a mock function with given fields: ctx, wg
func (_m *DatabaseService) Open(ctx context.Context, wg *sync.WaitGroup) (*sql.DB, error) {
	ret := _m.Called(ctx, wg)

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func(context.Context, *sync.WaitGroup) *sql.DB); ok {
		r0 = rf(ctx, wg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sync.WaitGroup) error); ok {
		r1 = rf(ctx, wg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
