// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	metric "github.com/djokcik/praktikum-go-devops/internal/metric"
	mock "github.com/stretchr/testify/mock"
)

// GaugeService is an autogenerated mock type for the GaugeService type
type GaugeService struct {
	mock.Mock
}

// GetOne provides a mock function with given fields: name
func (_m *GaugeService) GetOne(name string) (metric.Gauge, error) {
	ret := _m.Called(name)

	var r0 metric.Gauge
	if rf, ok := ret.Get(0).(func(string) metric.Gauge); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(metric.Gauge)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *GaugeService) List() ([]metric.Metric, error) {
	ret := _m.Called()

	var r0 []metric.Metric
	if rf, ok := ret.Get(0).(func() []metric.Metric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric.Metric)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: name, value
func (_m *GaugeService) Update(name string, value metric.Gauge) (bool, error) {
	ret := _m.Called(name, value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, metric.Gauge) bool); ok {
		r0 = rf(name, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, metric.Gauge) error); ok {
		r1 = rf(name, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
